/**
 * C AST Processor Module.
 */

import { CAstRoot } from "~src/parser/c-ast/core";
import { FunctionDataType } from "~src/parser/c-ast/dataTypes";
import { CAstRootP } from "~src/processor/c-ast/core";
import processFunctionDefinition from "~src/processor/functionUtil";
import processDeclaration from "~src/processor/processDeclaration";
import { SymbolTable } from "~src/processor/symbolTable";

/**
 * Processes the C AST tree generated by parsing, to add additional needed information for certain nodes.
 * @param ast
 * @param sourceCode
 * @returns
 */
export default function process(ast: CAstRoot, externalFunctions?: Record<string, FunctionDataType>) {
  const symbolTable = new SymbolTable();
  symbolTable.setExternalFunctions(externalFunctions?? {});
  const processedAst: CAstRootP = {
    type: "Root",
    functions: [],
    statements: [],
  };
  ast.children.forEach((child) => {
    // special handling for function definitions
    if (child.type === "FunctionDefinition") {
      processedAst.functions.push(
        processFunctionDefinition(child, symbolTable)
      );
    } else {
      const processedNode = processDeclaration(child, symbolTable);
      processedNode.forEach((statement) =>
        processedAst.statements.push(statement)
      );
    }
  });
  return processedAst;
}
